[2023-01-08 09:08:46,229] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-08T09:08:43.787262+00:00 [queued]>
[2023-01-08 09:08:46,234] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-08T09:08:43.787262+00:00 [queued]>
[2023-01-08 09:08:46,234] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 09:08:46,234] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-01-08 09:08:46,234] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 09:08:46,246] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): building_db_test> on 2023-01-08 09:08:43.787262+00:00
[2023-01-08 09:08:46,250] {standard_task_runner.py:52} INFO - Started process 5709 to run task
[2023-01-08 09:08:46,258] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_Scoring_Data_Engineering_Pipeline_test', 'building_db_test', 'manual__2023-01-08T09:08:43.787262+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_data_pipeline/unit_test/.ipynb_checkpoints/lead_scoring_data_pipeline_test-checkpoint.py', '--cfg-path', '/tmp/tmpg0tytglu', '--error-file', '/tmp/tmpj7xp3byc']
[2023-01-08 09:08:46,260] {standard_task_runner.py:80} INFO - Job 56: Subtask building_db_test
[2023-01-08 09:08:46,311] {task_command.py:371} INFO - Running <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-08T09:08:43.787262+00:00 [running]> on host 1f037b111ba5
[2023-01-08 09:08:46,361] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_Scoring_Data_Engineering_Pipeline_test
AIRFLOW_CTX_TASK_ID=building_db_test
AIRFLOW_CTX_EXECUTION_DATE=2023-01-08T09:08:43.787262+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-08T09:08:43.787262+00:00
[2023-01-08 09:08:46,362] {logging_mixin.py:115} INFO - DBPath/home/airflow/dags/Lead_scoring_data_pipeline/unit_test/utils_output.db
[2023-01-08 09:08:46,362] {logging_mixin.py:115} INFO - DB Already Exsist
[2023-01-08 09:08:46,427] {logging_mixin.py:115} WARNING - /home/airflow/dags/Lead_scoring_data_pipeline/unit_test/utils.py:200 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-08 09:08:46,430] {logging_mixin.py:115} WARNING - /home/airflow/dags/Lead_scoring_data_pipeline/unit_test/utils.py:209 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-08 09:08:46,434] {logging_mixin.py:115} WARNING - /home/airflow/dags/Lead_scoring_data_pipeline/unit_test/utils.py:218 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-08 09:08:46,530] {logging_mixin.py:115} INFO - df.shape[0] :100
[2023-01-08 09:08:46,530] {logging_mixin.py:115} INFO - df_test.shape[0] :100
[2023-01-08 09:08:46,530] {python.py:173} INFO - Done. Returned value was: None
[2023-01-08 09:08:46,537] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=Lead_Scoring_Data_Engineering_Pipeline_test, task_id=building_db_test, execution_date=20230108T090843, start_date=20230108T090846, end_date=20230108T090846
[2023-01-08 09:08:46,585] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-08 09:08:46,612] {local_task_job.py:273} INFO - 3 downstream tasks scheduled from follow-on schedule check
